version: '3.9'
networks:
  lab02-roteador:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 200.120.1.0/24
          gateway: 200.120.1.254
  lab02-net1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254
  lab02-net2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.254
  lab02-net3:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/8
          gateway: 10.1.1.254
services:
  R1:
    image: netensina/dockerlabs:latest
    volumes:
      - ./netensina:/netensina
    networks:
      lab02-roteador:
        ipv4_address: 200.120.1.1
      lab02-net1:
        ipv4_address: 192.168.1.101
      lab02-net2:
        ipv4_address: 192.168.2.102
    tty: true
    stdin_open: true
    privileged: true
    container_name: R1
  R2:
    image: netensina/dockerlabs:latest
    volumes:
      - ./netensina:/netensina
    networks:
      lab02-roteador:
        ipv4_address: 200.120.1.2
      lab02-net3:
        ipv4_address: 10.1.1.100
    tty: true
    stdin_open: true
    privileged: true
    container_name: R2
    depends_on:
      - R1
  H1:
    image: netensina/dockerlabs:latest
    volumes:
      - ./netensina:/netensina
    networks:
      lab02-net1:
        ipv4_address: 192.168.1.1 
    tty: true
    stdin_open: true
    privileged: true
    container_name: H1
    depends_on:
      - R1
  H2:
    image: netensina/dockerlabs:latest
    volumes:
      - ./netensina:/netensina 
    networks:
      lab02-net2:
        ipv4_address: 192.168.2.2
    tty: true
    stdin_open: true
    privileged: true
    container_name: H2
    depends_on:
      - R1
  H3:
    image: netensina/dockerlabs:latest
    volumes:
      - ./netensina:/netensina
    networks:
      lab02-net3:
        ipv4_address: 10.1.1.3
    tty: true
    stdin_open: true
    privileged: true
    container_name: H3
    depends_on:
      - R2
  H4:
    image: netensina/dockerlabs:latest
    volumes:
      - ./netensina:/netensina
    networks:
      lab02-net3:
        ipv4_address: 10.1.1.4
    tty: true
    stdin_open: true
    privileged: true
    container_name: H4
    depends_on:
      - R2