version: '3.9'
networks:
  redelab01:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/8
          gateway: 10.0.0.254
services:
  pc1:
    image: netensina/dockerlabs:latest
    volumes:
      - ./netensina:/netensina
    networks:
      redelab01:
        ipv4_address: 10.0.0.10
    tty: true
    stdin_open: true
    privileged: true
    container_name: CLIENTE
  pc2:
    image: netensina/dockerlabs:latest
    volumes:
      - ./netensina:/netensina
    networks:
      redelab01:
        ipv4_address: 10.0.0.20
    tty: true
    stdin_open: true
    privileged: true
    container_name: SERVIDOR